[package]
name = "mini-repl"
version = "0.1.0"
authors = ["delma <delma@del.ma>"]

[dependencies]
mini-pl = {path = "../mini-pl"}
clap = "2.28.0"
nom = "3.2.0"
termion = "1.5.1"
failure = "0.1.1"
failure_derive = "0.1.1"
unicode-width = "0.1.4"