[package]
name = "mini-pl"
version = "0.1.0"
authors = ["delma <delma@del.ma>"]

[dependencies]
parsco = {path = "../parsco"}
num-bigint = "0.1.41"
num-rational = "0.1.41" 
num-traits = "0.1.41"
unicode-segmentation = "1.1.0"
char_stream = "0.1.8"
